config/routes.rb
Rails.application.routes.draw do
  root to: "journalists#index"
  resources :journalists, only: [
  	:index,
  	:new,
  	:create,
  	:show,
  	:destroy,
  	:update,
    :edit]
end

app/models/journalist.rb
class Journalist < ActiveRecord::Base

  validates :name, :media, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/journalists_controller.rb
class JournalistsController < ApplicationController

  def index
    @journalists = Journalist.all 	
  end

  def show
    @journalist = journalist
  end

  def new
    @journalist = Journalist.new
  end

  def create
    @journalist = Journalist.create(params_journalist)
    if @journalist.save
      flash[:success] = "The journalist was successfully added!"
      redirect_to root_path
    else
      render :new
      flash[:error] = "Some of the fields placed errors, please check. #{ '<br>- ' + @journalist.errors.full_messages.join(' <br>- ')}".html_safe
    end
  end

  def edit
    @journalist = journalist
  end

  def update
    @journalist = journalist
    if @journalist.update(params_journalist)
      flash[:success] = "The journalist was successfully updated!"
      redirect_to root_path
    else
      render :edit
      flash[:error] = "Some of the fields placed errors, please check. #{ '<br>- ' + @journalist.errors.full_messages.join(' <br>- ')}".html_safe
    end
  end

  def destroy
    journalist.destroy
    flash[:success] = "The journalist was successfully deleted!"
    redirect_to root_path
  end

  private

  def params_journalist
    params.require(:journalist).permit(:name, :media)
  end

  def journalist
  	Journalist.find_by_id(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journalists_helper.rb
module JournalistsHelper

  def button_name(action)
    action == "new" ? "Create" : "Update"
  end
end

app/views/journalists/_form.slim
= form_for(@journalist) do |f|
  = render 'shared/errors', object: @journalist
  #action.hidden #{params[:action]}
  #id.hidden #{@journalist.id}
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', required: true
  .form-group
    = f.label :media
    = f.text_field :media, class: 'form-control', required: true
  = f.submit "#{button_name(params[:action])}", class: "btn btn-primary"

app/views/journalists/_header.slim
.col-md-12
  h4.float-right
    | Made by: 
    = link_to "Genesis Gonzalez", "https://ve.linkedin.com/in/genesis-gonzalez-479814109", target: "_blank"

hr.col-md-12

.col-md-6
  h1 Journalists
.col-md-6
  = link_to "Add Journalist", new_journalist_path, class: "btn btn-primary", remote: true, "data-toggle" => "modal", "data-target" => "#new-journalist", id: "new-journalist-button"

app/views/journalists/_new_modal.slim
#new-journalist.modal.fade role="dialog"
  .modal-dialog
    .modal-content
      .modal-header
        button.close data-dismiss="modal" type="button"  &times;
        h4.modal-title New Journalist
      .modal-body
        p .
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button"  Close

app/views/journalists/edit.js.erb
$("#new-journalist .modal-body").html('<%= render "journalists/form" %>');

app/views/journalists/index.slim
= render 'header'

table#journalists.table.table-striped.table-responsive
  thead
    tr
      th Name
      th Media
      th
      th
  tbody
    - if @journalists.blank?
      tr
        td colspan="4" No Journalists
    - @journalists.each do |journalist|
      tr
        td=journalist.name
        td=journalist.media
        td= link_to "Update", edit_journalist_path(journalist), method: :get, remote: true, "data-toggle" => "modal", "data-target" => "#new-journalist"
        td= link_to 'Destroy', { action: :destroy, id: journalist.id }, method: :delete, data: { confirm: 'Are you sure?' }

= render 'new_modal'

app/views/journalists/new.js.erb
$("#new-journalist .modal-body").html('<%= render "journalists/form" %>');

app/views/journalists/new.slim
div class="row"
  div class="col-md-6 col-md-offset-3"
    = render 'form'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZimplePr</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |key, value| %>
            <%= content_tag :div, value, class: "flash alert alert-#{key}" %>
          <% end %>

          <%= yield %>
        </div>
    </div>
    </div>
  </body>
</html>

app/views/shared/_errors.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      | The form contains 
      = pluralize(object.errors.count, "error")
      | .
    ul
      - object.errors.full_messages.each do |msg|
        li* = msg